### ISSUE TITLE
Apply License to GitHub

### ISSUE THREAD

**Issue by lukevp** [mist64/perfect6502#6]
Hello,

The comment text of the perfect6502.c file appears to grant usage of that file under the MIT license. However, the readme does not contain the license, and it is not tagged on GitHub as being under the MIT license, so it could be possibly construed that not all of the files are MIT.  This is probably not your intent, so I was hoping you could apply the MIT license on GitHub as well as adding a comment to the readme.

Here is an example repo of mine that is MIT so you can see where it shows on GitHub. https://github.com/lukevp/ESC-POS-.NET

**Comment by mist64** [comment]
d4117f915f9d741da50c61f254389ec6f36c17cc
